dubbo.registry.address=zookeeper://zk.beta.corp.qunar.com:2181
dubbo.registry.group=mkt_push_engine_server

logging.level.com.qunar.marketing.mkt.pub.alg.tfserving.push.engine.server.service.utils.model.Model=DEBUG