#organization=marketing
#owner=[nanneron.chen, dengfeng.zhang]
#developer=[dengfeng.zhang]
#mailGroup=[nanneron.chen@qunar.com, dengfeng.zhang@qunar.com]
name=mkt_push_engine_server
token=I+yw1W7sEpEvcqLe6GzKHxdSP7IQwwS2WYguriYGB+moGnKaXjUUy71QVxwnvCsvY6zJMWRuinFABKjjt1dsC+6AZC5owjjO/keStOA4JPeQxA9ifdZiLsFSnEwcTg+uqiByp32KlWwnwo3jC5GQkcgynPuR9vfCaP5HLUjuV14=
