redis.featureStorage.namespace=redis-noah_push-engine-server
redis.featureStorage.cipher=be1e8df1
redis.featureStorage.timeout=5000
redis.featureStorage.poolCoreSize=100
redis.featureStorage.poolMaxSize=200
redis.featureStorage.zkAddr=dbazk.beta.qunar.com:2181


redis.featureStorage1.namespace=redis-noah_push-engine-server
redis.featureStorage1.cipher=be1e8df1
redis.featureStorage1.timeout=5000
redis.featureStorage1.poolCoreSize=100
redis.featureStorage1.poolMaxSize=200
redis.featureStorage1.zkAddr=dbazk.beta.qunar.com:2181


redis.featureStorage2.namespace=redis-noah_push-engine-server
redis.featureStorage2.cipher=be1e8df1
redis.featureStorage2.timeout=5000
redis.featureStorage2.poolCoreSize=100
redis.featureStorage2.poolMaxSize=200
redis.featureStorage2.zkAddr=dbazk.beta.qunar.com:2181