aws.oss.endPoint=http://mkt-push-engine-server.oss.corp.qunar.com
aws.oss.bucket=mkt_push_engine_server_0001
aws.oss.accessKey=b46495534705e02ade1a2a1293cbcd87
aws.oss.secretKey=b46495534705e02ade1a2a1293cbcd87