server.port=8080

# 页面默认前缀目录
spring.mvc.view.prefix=/WEB-INF/templates/
# 响应页面默认后缀
spring.mvc.view.suffix=.jsp

dubbo.application.name=mkt_push_engine_server
dubbo.registry.address=zookeeper://zk.beta.corp.qunar.com:2181
dubbo.registry.group=mkt_push_engine_server
