created-time=2025-09-10 17:26:41
created-by=null
starter-version=1.1
group-id=com.qunar.marketing.mkt.pub.alg.tfserving
artifact-id=mkt_push_engine_server
version=1.0.0
package=com.qunar.marketing.mkt.pub.alg.tfserving.push.engine.server
spring-boot=true
facet=common